<?php

define('BASEURL', $_ENV['BASEURL']);
define('RECAPTCHA_SITE_KEY', $_ENV['RECAPTCHA_SITE_KEY']);
define('RECAPTCHA_SECRET_KEY', $_ENV['RECAPTCHA_SECRET_KEY']);
define('CSRF_SECRET_KEY', $_ENV['CSRF_SECRET_KEY']);